name: Deploy

on:
  workflow_run:
    workflows: [Build]
    types: [completed]
    branches: [master]

permissions:
  contents: read
  actions: read

jobs:
  publish-extension:
    name: Publish to marketplace
    runs-on: ubuntu-latest
    environment: Production
    if: ${{ github.event.workflow_run.conclusion == 'success' }}

    steps:
      - name: Download artifacts
        uses: dawidd6/action-download-artifact@v19
        with:
          workflow: build.yaml
          run_id: ${{ github.event.workflow_run.id }}

      - name: Publish to Visual Studio Marketplace
        run: npx vsce publish --packagePath $(find . -iname *.vsix)
        env:
          VSCE_PAT: ${{ secrets.VSCE_PAT }}
