name: Publish

on:
  workflow_run:
    workflows: [Build]
    types: [completed]
    branches: [master]

jobs:
  publish:
    runs-on: ubuntu-latest
    needs: build
    environment: Production
    if: success()
    steps:
      - uses: actions/download-artifact@v2
      - run: npx vsce publish --packagePath $(find . -iname *.vsix)
        env:
          VSCE_PAT: ${{ secrets.VSCE_PAT }}
